apiVersion : apps/v1
kind: Deployment
metadata:
  name: ordermanagement 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ordermanagement
  template:
    metadata:
      labels:
        app: ordermanagement 
    spec:
      containers:
        - name: ordermanagement 
          image: crsoftwarearchitecturetest.azurecr.io/ordermanagement
          ports:
          - containerPort: 8080