apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordermanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordermanagement
  template:
    metadata:
      labels:
        app: ordermanagement
    spec:
      containers:
      - name: ordermanagement
        image: ordermanagement
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ConnectionStrings__DefaultConnection
          value: "Server=mssql,1433;Database=ecomerce;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True"
        - name: RabbitMQ__HostName
          value: "rabbitmq"
        - name: RabbitMQ__UserName
          value: "guest"
        - name: RabbitMQ__Password
          value: "guest"
---
apiVersion: v1
kind: Service
metadata:
  name: ordermanagement
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: ordermanagement