trigger:
  branches:
    include:
    - main
  paths:
    include:
    - kubernetes-aks/**

resources:
- repo: self

variables:
  vmImageName: 'ubuntu-latest'

stages:
- stage: Deploy
  displayName: Deploy Stage
  jobs:
  - deployment: Deploy
    displayName: Deploy RabbitMQ to Kubernetes
    environment: 'ipacbalajsoftwarearchitecture.default'
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self  # Explicitly checkout the repository. In case of deployments the checkout does not automaticall happen
          - task: KubernetesManifest@0
            displayName: Deploy RabbitMQ to Kubernetes
            inputs:
              action: deploy
              manifests: |
                $(System.DefaultWorkingDirectory)/kubernetes-aks/rabbit-aks-deployment.yml
